In [1]:
%load_ext autoreload
# %autoreload 2

In [2]:
%autoreload 2
from src import matriz_aumentada, gauss_jordan

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b) # type: ignore
gauss_jordan(Ab)

[01-29 13:10:18][INFO][DELL] 2026-01-29 13:10:18.196506
[01-29 13:10:18][INFO][DELL] 2026-01-29 13:10:18.566793
[01-29 13:10:18][INFO][DELL] 2026-01-29 13:10:18.579540
[01-29 13:10:18][INFO][DELL] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[01-29 13:10:18][INFO][DELL] 
[[ 1.  0.  3.  6.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[01-29 13:10:18][INFO][DELL] 
[[ 1.  0.  0. -3.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
[01-29 13:10:18][INFO][DELL] 
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0. -6.]
 [ 0.  0. -1.  0. -6.]
 [ 0.  0.  0.  2. -4.]]


array([ 3., -6.,  6., -2.])

# Resolver

In [3]:
import logging
from sys import stdout
from datetime import datetime
import os

logging.basicConfig(
    level=logging.INFO,
    format=f"[%(asctime)s][%(levelname)s][{os.environ.get('USERNAME')}] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-29 13:11:05][INFO][DELL] 2026-01-29 13:11:05.200571


In [18]:
import numpy as np
from pprint import pprint

# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante método de Gauss-Jordan.
    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    # COMPLETAR
    # Debe basarse en la función gauss_jordan
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(
            A, dtype=float
        )  # convertir en float, porque si no, convierte en enteros
    #assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            logging.info(f"\n{A}")
            raise ValueError("No existe solución única.")

        if p != i:
            logging.info(f"Intercambiando filas {i} y {p}.")
            # swap rows
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

        A[i, :] = A[i, :] / A[i, i]  # normalize pivot row

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")
    
        print(f"\n{A}")

    return A

* Ejercicio 1

In [19]:
A = [[2, -3], [-1, 1]]
gauss_jordan(A)

[01-29 13:25:11][INFO][DELL] Intercambiando filas 0 y 1.
[01-29 13:25:11][INFO][DELL] 
[[ 1. -1.]
 [ 0. -1.]]
[01-29 13:25:11][INFO][DELL] 
[[ 1.  0.]
 [-0.  1.]]


array([[ 1.,  0.],
       [-0.,  1.]])

In [20]:
n = len (A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[ 2., -3.,  1.,  0.],
       [-1.,  1.,  0.,  1.]])

In [21]:
m_inv = gauss_jordan(A_aug)
m_inv

[01-29 13:25:58][INFO][DELL] Intercambiando filas 0 y 1.
[01-29 13:25:58][INFO][DELL] 
[[ 1. -1. -0. -1.]
 [ 0. -1.  1.  2.]]
[01-29 13:25:58][INFO][DELL] 
[[ 1.  0. -1. -3.]
 [-0.  1. -1. -2.]]


array([[ 1.,  0., -1., -3.],
       [-0.,  1., -1., -2.]])

* Ejercicio 2

In [22]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
gauss_jordan(A)

[01-29 13:27:29][INFO][DELL] Intercambiando filas 0 y 1.
[01-29 13:27:29][INFO][DELL] 
[[  1.   0.   4.   0.]
 [  0.   0. -16.   5.]
 [  0.   4. -11.   3.]
 [  0.   3.  -1.   0.]]
[01-29 13:27:29][INFO][DELL] Intercambiando filas 1 y 3.
[01-29 13:27:29][INFO][DELL] 
[[  1.           0.           4.           0.        ]
 [  0.           1.          -0.33333333   0.        ]
 [  0.           0.          -9.66666667   3.        ]
 [  0.           0.         -16.           5.        ]]
[01-29 13:27:29][INFO][DELL] 
[[ 1.          0.          0.          1.24137931]
 [ 0.          1.          0.         -0.10344828]
 [-0.         -0.          1.         -0.31034483]
 [ 0.          0.          0.          0.03448276]]
[01-29 13:27:29][INFO][DELL] 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [ 0.  0.  0.  1.]]


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [23]:
n = len (A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[4., 0., 0., 5., 1., 0., 0., 0.],
       [1., 0., 4., 0., 0., 1., 0., 0.],
       [3., 4., 1., 3., 0., 0., 1., 0.],
       [1., 3., 3., 0., 0., 0., 0., 1.]])

In [24]:
m_inv = gauss_jordan(A_aug)
m_inv

[01-29 13:27:54][INFO][DELL] Intercambiando filas 0 y 1.
[01-29 13:27:54][INFO][DELL] 
[[  1.   0.   4.   0.   0.   1.   0.   0.]
 [  0.   0. -16.   5.   1.  -4.   0.   0.]
 [  0.   4. -11.   3.   0.  -3.   1.   0.]
 [  0.   3.  -1.   0.   0.  -1.   0.   1.]]
[01-29 13:27:54][INFO][DELL] Intercambiando filas 1 y 3.
[01-29 13:27:54][INFO][DELL] 
[[  1.           0.           4.           0.           0.
    1.           0.           0.        ]
 [  0.           1.          -0.33333333   0.           0.
   -0.33333333   0.           0.33333333]
 [  0.           0.          -9.66666667   3.           0.
   -1.66666667   1.          -1.33333333]
 [  0.           0.         -16.           5.           1.
   -4.           0.           0.        ]]
[01-29 13:27:54][INFO][DELL] 
[[ 1.          0.          0.          1.24137931  0.          0.31034483
   0.4137931  -0.55172414]
 [ 0.          1.          0.         -0.10344828  0.         -0.27586207
  -0.03448276  0.37931034]
 [-0.         -0

array([[  1.,   0.,   0.,   0., -36.,  45.,  60., -80.],
       [  0.,   1.,   0.,   0.,   3.,  -4.,  -5.,   7.],
       [ -0.,  -0.,   1.,   0.,   9., -11., -15.,  20.],
       [  0.,   0.,   0.,   1.,  29., -36., -48.,  64.]])

* Ejercicio 3

In [25]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
gauss_jordan(A)

[01-29 13:29:17][INFO][DELL] Intercambiando filas 0 y 2.
[01-29 13:29:17][INFO][DELL] 
[[ 1.  1. -0. -0. -2. -1. -0. -0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.]
 [ 0.  2.  1.  0. -3. -2.  0.  2.]
 [ 0.  1.  0.  0. -1. -1.  0.  0.]
 [ 0. -2. -1.  1.  4.  2.  0.  2.]
 [ 0. -2.  0.  0.  4.  3.  2.  0.]]
[01-29 13:29:17][INFO][DELL] 
[[ 1.  0.  1. -1. -2.  0. -0. -1.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  3. -2. -3.  0.  0.  0.]
 [ 0.  0.  1. -1. -1.  0.  0. -1.]
 [ 0.  0. -3.  3.  4.  0.  0.  4.]
 [ 0.  0. -2.  2.  4.  1.  2.  2.]]
[01-29 13:29:17][INFO][DELL] Intercambiando filas 2 y 3.
[01-29 13:29:17][INFO][DELL] 
[[ 1.  0.  0.  0. -2. -1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  1. -1. -0.  1. -0. -1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  1. -3. -3.  0.  3.]
 [ 0.  0.  0.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0.  4.  3

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [-0., -0., -0., -0.,  1.,  0.,  0.,  0.],
       [-0., -0., -0., -0., -0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [26]:
n = len (A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  1., -1.,  1.,  0., -1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [-1., -1.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.],
       [-1., -1., -1.,  1.,  2.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.],
       [-1.,  1.,  1.,  0., -1., -1.,  0.,  2.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.],
       [ 0.,  1.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.],
       [ 1., -1., -1.,  1.,  2.,  1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.],
       [ 2.,  0.,  0.,  0.,  0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.]])

In [27]:
m_inv = gauss_jordan(A_aug)
m_inv

[01-29 13:29:45][INFO][DELL] Intercambiando filas 0 y 2.
[01-29 13:29:45][INFO][DELL] 
[[ 1.  1. -0. -0. -2. -1. -0. -0. -0. -0. -1. -0. -0. -0. -0. -0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  2.  1.  0. -3. -2.  0.  2.  0.  0. -1.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0. -2. -1.  1.  4.  2.  0.  2.  0.  0.  1.  0.  0.  0.  1.  0.]
 [ 0. -2.  0.  0.  4.  3.  2.  0.  0.  0.  2.  0.  0.  0.  0.  1.]]
[01-29 13:29:45][INFO][DELL] 
[[ 1.  0.  1. -1. -2.  0. -0. -1. -0. -1. -1. -0. -0. -0. -0. -0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  0.  3. -2. -3.  0.  0.  0.  0. -2. -1.  0.  1.  0.  0.  0.]
 [ 0.  0.  

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2., -1.,  0., -1.,  0.,
         2.,  2., -1.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1., -1.,  0.,
         0.,  0.,  0.],
       [-0., -0.,  1.,  0.,  0.,  0.,  0.,  0.,  6., -1.,  0., -3.,  1.,
         1.,  4., -3.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  6.,  1., -1., -3.,  1.,
        -3.,  3., -3.],
       [-0., -0., -0., -0.,  1.,  0.,  0.,  0.,  2., -1.,  1., -1.,  0.,
         3.,  2., -1.],
       [-0., -0., -0., -0., -0.,  1.,  0.,  0., -2.,  2.,  0.,  0.,  0.,
        -4., -2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., -1.,  0.,  0.,  1.,  0.,
         0., -1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  0.,  0.,  1.,  0.,
         0., -1.,  1.]])

* Ejercicio 4

In [28]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
gauss_jordan(A)

[01-29 13:29:56][INFO][DELL] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.]]
[01-29 13:29:56][INFO][DELL] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1.]
 [ 0.  0.  1.  1.  2. -1. -1. -1. -2.  2.]
 [ 0.  0.  1.  2.  1. -1.  1.  1. -1.  1.]
 [ 0.  0.  1.  2.  2. -1. -1. -1. -1.  1.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.]]
[01-29 13:29:56][INFO][DELL] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.]
 [ 0.

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0., -0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0., -0., -0., -0.,  1.,  0.,  0.,  0.,  0.],
       [-0., -0., -0., -0., -0., -0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [29]:
n = len (A)
A_aug = np.hstack((A, np.eye(n)))
A_aug

array([[ 1.,  0.,  0.,  0., -1.,  0.,  0., -1.,  1., -1.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0., -1., -1.,  1.,  0.,  0.,  1., -1.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0., -1.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0., -1., -1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0., -1.,  1.,  1.,  1.,  1.,  0., -1.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1., -1., -1., -1.,  1., -1.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  1.,  0., -1., -1., -1.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0., -1., -1.,  0.,  0.,  0.,  

In [30]:
m_inv = gauss_jordan(A_aug)
m_inv

[01-29 13:30:11][INFO][DELL] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.  1.  0.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.  1.  0.  0.  0.  1.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1. -1.  0.  0.  0.  0.  1.  0.  0.
   0.  0.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2. -1.  0.  0.  0.  0.  0.  1.  0.
   0.  0.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1. -1.  0.  0.  0.  0.  0.  0.  1.
   0.  0.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1. -1.  0.  0.  0.  0.  0.  0.  0.
   1.  0.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.]]
[01-29 13:30:11][INFO][DELL] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  14.,
         -8.,   9.,  -4.,   0.,  -4.,   9.,   7.,  -8.,   3.],
       [  0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  -2.,
          2.,  -1.,   2.,   1.,   1.,  -1.,  -1.,   1.,  -2.],
       [ -0.,  -0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0., -27.,
         14., -18.,   5.,  -2.,   7., -17., -13.,  16.,  -2.],
       [ -0.,  -0.,  -0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,  12.,
         -6.,   8.,  -2.,   1.,  -3.,   7.,   6.,  -7.,   0.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   6.,
         -4.,   4.,  -2.,   0.,  -2.,   4.,   3.,  -3.,   2.],
       [ -0.,  -0.,  -0.,  -0.,  -0.,   1.,   0.,   0.,   0.,   0.,  18.,
         -9.,  12.,  -4.,   1.,  -5.,  11.,   9., -11.,   1.],
       [ -0.,  -0.,  -0.,  -0.,  -0.,  -0.,   1.,   0.,   0.,   0.,   8.,
         -4.,   5.,  -1.,   1.,  -2.,   5.,   4.,  -5.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0